"""initial version

Revision ID: 422536e71ad6
Revises:
Create Date: 2024-08-06 14:46:57.164726

"""


# revision identifiers, used by Alembic.
revision = "422536e71ad6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
