"""add missing name column

Revision ID: c7509b8f755a
Revises: 422536e71ad6
Create Date: 2024-08-06 18:24:34.200496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7509b8f755a"
down_revision = "422536e71ad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "name")
    # ### end Alembic commands ###
