name: Static testing
on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronized, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Setup Python 3.12.4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
    - name: Pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files
      